server:
    port: 8083
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: bansis-client
                  uri: lb://bansis-client
                  predicates:
                    - Path=/clients/**
                - id: bansis-current-account
                  uri: lb://bansis-current-account
                  predicates:
                    - Path=/cu-accounts/**
                - id: bansis-savings-fixed-account
                  uri: lb://bansis-savings-fixed-account
                  predicates:
                    - Path=/accounts/**
                - id: bansis-yanki-wallet
                  uri: lb://bansis-yanki-wallet
                  predicates:
                    - Path=/yanki/**
                - id: bansis-bootcoin
                  uri: lb://bansis-bootcoin
                  predicates:
                    - Path=/bootcoin/**
